### ISSUE TITLE
Update metadescriptions for homepage & each category page

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#110]
@missgene can you help draft something for each of the pages you see are missing? maybe you can make a google doc and then we update in the frontend

**Comment by missgene** [comment]
Here's the spreadsheet I've prepared: https://docs.google.com/spreadsheets/d/1jq-PNmtghSsNoJAFrRMM2JP87atAofmHgkLbJ21SpZw/edit?usp=sharing 

I'm going to add more details..

**Comment by missgene** [comment]
Hi @laurenluz! Just checking in what we need to do here? The meta description suggestions have been added too :) Thank you!

**Comment by ahmadabugosh** [comment]
hey @missgene , sent this on chat, but sending here  too just to keep track. 

1) We need to add Page titles too, because the ones we have are default and don't look good on the Search Engine Results Page. 
2) I think we should include the keywords "ENS swag" and "ENS merch" everywhere that we can because those are the terms people mainly search for, so include that in each title and meta description where it makes sense.
3) We should also use the word "official ENS" wherever we can because it is official merch for example instead of saying high quality merch, you could say official ENS merch etc.
