### ISSUE TITLE
Sort names alphabetically in the drop down

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/ens-merch-shop#35]
### Describe the feature you'd like to request

Sort names alphabetically in the drop down for all the different names... but sort by the base ENS name... so it would be like:

fun.eth
giv.eth
liquidity.giv.eth
otc.giv.eth
heaven.eth

**Comment by ahmadabugosh** [comment]
Hey @RamRamez I don't think this is exactly what @GriffGreen wanted. 

The sorting worked alphabetically, but if you have a secondary ENS name (like .giv.eth or .griff.eth for example), those names should appear after their parent name. 

For example, it should be 
1) 
griff.eth
**green.griff.eth** (it appears under because it is a "subdomain" of griff.eth)
then the others continue like:
griffdog.eth 
griffgreen.eth etc.

2)  The secondary names should also be sorted alphabetically like:
giv.eth
**grants.giv.eth** (they appear under because they  are "subdomain" of giv.eth)
**liquidity.giv.eth**
**otc.giv.eth**
then the others continue like: 
give.eth
giveth.eth etc. 

-----

Does that make sense?

**Comment by RamRamez** [comment]
I fixed it in PR #92 

Thanks ChatGPT for solving this complex sorting problem.
